language : java
jdk: 
   -openjdk8
   
branches:
   only:
   - main
   
# travis 서버의 home
cache :
   directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'
script : "./gradlew clean build"
notifications:
   email:
      recipients:
         - jw00n0212@gmail.com
