language : java
jdk: 
   -openjdk8
   
branches:
   only:
   - main
   
# travis 서버의 home
cache :
   directories:
      - '$HOME/.m2/repository'
      - '$HOME/demo/.gradle'
script : 
   - cd demo
   - ./gradlew clean build

before_deploy:
   - pwd
   - zip -r momodemo-server *
   - mkdir -p deploy
   - mv momodemo-server.zip deploy/momodemo-server.zip

deploy:
   - provider: s3
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: $AWS_SECRET_KEY
     bucket: momo-demo-build
     region: ap-northeast-2
     skip_cleanup: true
     aci: private
     local_dir: deploy
     wait-until-deployed: true
     on: 
         all_branches: true
         
   - provider: codedeploy
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: $AWS_SECRET_KEY
     bucket: momo-demo-build
     key: momodemo-server.zip
     bundle_type: zip
     application: momo-demoserver
     deployment_group: momo-demoserver-group
     region: ap-northeast-2
     wait-until-deployed: true
    
    
notifications:
   email:
      recipients:
         - jw00n0212@gmail.com
